import type { Category } from './catalog';
import type { Locale } from './i18n';

const ar = {
  meta: {
    title: 'سراب | المجموعة الأولى',
    description: 'سراب: معاطف وعبايات وقطع من الصوف والكتان والجلد بألوان الرمل والليل. متجر تجريبي من تصميم سيما ستوديو.',
  },
  nav: {
    women: 'النساء',
    men: 'الرجال',
    accessories: 'الإكسسوارات',
    story: 'قصتنا',
    shopAll: 'المتجر',
    bag: 'الحقيبة',
    menu: 'القائمة',
    close: 'إغلاق',
    lang: 'English',
    langShort: 'EN',
    langHref: '/en',
  },
  category: {
    women: 'النساء',
    men: 'الرجال',
    accessories: 'الإكسسوارات',
  } satisfies Record<Category, string>,
  hero: {
    label: 'فيديو: الكاميرا تبتعد عن قماش معطف الدهناء حتى تظهر عارضة واقفة على كثيب رملي.',
    collection: 'المجموعة الأولى',
    cloth: 'صوف بوجهين، وحواف مخيطة يدويًا',
    season: 'خريف وشتاء 2026',
    shop: 'تسوّقوا المجموعة',
    tagShop: 'تسوّقوا',
    hint: 'مرّروا للأسفل',
  },
  home: {
    edit: 'المجموعة الأولى',
    editLead: 'ثماني قطع من الصوف والكتان والجلد، بألوان الرملي والعاجي والكحلي.',
    viewAll: 'عرض الكل',
    featureKicker: 'معطف الدهناء',
    featureTitle: 'قطعة الموسم',
    featureBody:
      'معطف طويل من الصوف بوجهين، بقصّة مستقيمة وكتف منسدل. بلا بطانة، لذلك يبقى خفيفًا في شتاء الرياض ودافئًا في الصباحات الباردة.',
    featureCta: 'تسوّقوا المعطف',
    shopBy: 'تسوّقوا حسب الفئة',
    nightKicker: 'للمساء',
    nightTitle: 'عباية ليل، ومعطف الدهناء باللون الكحلي',
    nightBody: 'عباية من الكريب الأسود المطفي، والمعطف نفسه باللون الكحلي. قطعتان للسهرات والأمسيات الباردة.',
    nightCta: 'تسوّقوا عباية ليل',
    sunsetAhead: (time: string) => `غروب الشمس في الرياض اليوم: ${time}`,
    sunsetPast: (time: string) => `غربت الشمس في الرياض اليوم الساعة ${time}`,
    storyKicker: 'قصتنا',
    storyTitle: 'ملابس تناسب أجواءنا',
    storyBody: 'شتاؤنا قصير، والصباح بارد والظهيرة دافئة. لذلك نختار أقمشة لها وزن، وقصّات واسعة، وألوانًا مأخوذة من الرمل.',
    storyCta: 'المزيد عن سراب',
  },
  service: [
    { title: 'التوصيل لجميع مناطق المملكة', text: 'خلال 2 إلى 4 أيام عمل، ومجاني للطلبات فوق 1,000 ر.س.' },
    { title: 'إرجاع مجاني خلال 14 يومًا', text: 'نستلم القطعة من باب بيتكم بدون أي رسوم.' },
    { title: 'تغليف هدايا مجاني', text: 'في علبة ورقية مع بطاقة مكتوبة بخط اليد.' },
  ],
  shop: {
    all: 'كل القطع',
    items: (n: number) => (n === 1 ? 'قطعة واحدة' : n === 2 ? 'قطعتان' : n <= 10 ? `${n} قطع` : `${n} قطعة`),
    colours: (n: number) => (n === 2 ? 'لونان' : n > 2 ? `${n} ألوان` : ''),
  },
  product: {
    colour: 'اللون',
    size: 'المقاس',
    sizeGuide: 'دليل المقاسات',
    selectSize: 'يرجى اختيار المقاس',
    add: 'إضافة إلى الحقيبة',
    added: 'تمت الإضافة إلى الحقيبة',
    details: 'تفاصيل المنتج',
    fit: 'المقاس والقصّة',
    fabric: 'الخامة والعناية',
    delivery: 'الشحن والإرجاع',
    deliveryText:
      'التوصيل لجميع مناطق المملكة خلال 2 إلى 4 أيام عمل، ومجاني للطلبات فوق 1,000 ر.س. يمكنكم إرجاع القطعة خلال 14 يومًا من الاستلام، بشرط أن تكون بحالتها الأصلية.',
    wearWith: 'أكملوا الإطلالة',
    home: 'الرئيسية',
    oneSize: 'مقاس واحد',
    gallery: (name: string, n: number) => `${name}، صورة ${n}`,
    zoom: 'تكبير الصورة',
    prev: 'السابقة',
    next: 'التالية',
  },
  sizeGuide: {
    title: 'دليل المقاسات',
    note: 'القياسات بالسنتيمتر، وهي قياسات الجسم وليست قياسات القطعة.',
    head: ['المقاس', 'الصدر', 'الخصر', 'الأرداف'],
  },
  bag: {
    title: 'الحقيبة',
    empty: 'حقيبة التسوق فارغة.',
    emptyCta: 'تسوّقوا المجموعة',
    remove: 'حذف',
    qty: 'الكمية',
    subtotal: 'المجموع',
    shippingNote: 'تُحسب رسوم الشحن عند إتمام الطلب.',
    checkout: 'إتمام الطلب',
    size: 'المقاس',
    colour: 'اللون',
  },
  checkout: {
    title: 'إتمام الطلب',
    summary: 'ملخص الطلب',
    delivery: 'الشحن',
    free: 'مجاني',
    total: 'الإجمالي',
    empty: 'لا توجد قطع في حقيبة التسوق.',
    demoKicker: 'متجر تجريبي',
    demoTitle: 'هنا تكون صفحة الدفع في متجركم.',
    demoBody:
      'سراب متجر تجريبي من تصميم وتنفيذ سيما ستوديو. القطع والصور والفيديو صُنعت لهذا العرض، ولا يتم أي دفع هنا. في متجركم، تُربط هذه الخطوة ببوابة الدفع التي تختارونها.',
    demoList: ['مدى وApple Pay عبر ميسّر', 'التقسيط مع تابي وتمارا', 'الربط مع سلة أو زد أو Shopify', 'فواتير إلكترونية متوافقة مع هيئة الزكاة'],
    demoCta: 'اطلبوا متجرًا مثل هذا',
    back: 'الرجوع إلى الحقيبة',
  },
  story: {
    kicker: 'قصتنا',
    title: 'ملابس تناسب أجواءنا.',
    paragraphs: [
      'بدأت سراب بسؤال بسيط: كيف يكون المعطف لو صُمّم للرياض، لا لمدينة باردة بعيدة؟ شتاؤنا قصير، والصباح بارد، والظهيرة دافئة، والهواء لا يهدأ.',
      'لذلك نختار أقمشة لها وزن، تنسدل بشكل مستقيم ولا تتطاير مع الهواء. نعتمد الكتف المنسدل والأكمام الواسعة، ونترك المعاطف بلا بطانة حتى تبقى خفيفة.',
      'وألواننا من المكان نفسه: رملي الدهناء، والعاجي، والكحلي. ثلاثة ألوان تتناسق مع بعضها مهما جمعتوها.',
    ],
    principles: [
      { title: 'أقمشة لها وزن', text: 'صوف بوجهين، وكريب مطفي، وكتان مغسول، وجلد مدبوغ نباتيًا.' },
      { title: 'قصّات واسعة', text: 'أكتاف منسدلة، وأكمام عريضة، وأطوال كاملة مريحة في الحركة.' },
      { title: 'كميات محدودة', text: 'نصنع كل قطعة بعدد محدود، ونعيد إنتاجها حسب الطلب فقط.' },
    ],
    care: {
      title: 'العناية بالقطع',
      text: 'نظّفوا الصوف بالفرشاة بعد كل استخدام، وعلّقوه على علّاقة عريضة. المعاطف والعبايات تنظيف جاف فقط، والكتان يُغسل باليد بماء بارد. أبعدوا الجلد عن الماء، ورطّبوه بكريم الجلد مرة كل موسم.',
    },
    cta: 'تسوّقوا المجموعة الأولى',
  },
  footer: {
    help: 'خدمة العملاء',
    helpLinks: ['الشحن والتوصيل', 'الإرجاع', 'دليل المقاسات', 'العناية بالقطع'],
    house: 'سراب',
    houseLinks: ['قصتنا', 'المجموعة الأولى'],
    demo: 'متجر تجريبي من تصميم وتنفيذ سيما ستوديو. القطع والصور والفيديو صُنعت لهذا العرض، وليست للبيع.',
    by: 'تصميم وتنفيذ',
    rights: '© 2026 سراب. جميع الحقوق محفوظة.',
  },
  notFound: {
    kicker: 'خطأ 404',
    title: 'الصفحة غير موجودة',
    body: 'ربما الرابط غير صحيح، أو أن الصفحة نُقلت.',
    cta: 'العودة إلى المتجر',
    suggest: 'قد يعجبكم أيضًا',
  },
};

type Copy = typeof ar;

const en: Copy = {
  meta: {
    title: 'SARAB — Collection 01',
    description: 'SARAB: coats, abayas and pieces in wool, linen and leather, in the colours of sand and night. A demo store designed by SIMA Studio.',
  },
  nav: {
    women: 'Women',
    men: 'Men',
    accessories: 'Accessories',
    story: 'Story',
    shopAll: 'Shop all',
    bag: 'Bag',
    menu: 'Menu',
    close: 'Close',
    lang: 'العربية',
    langShort: 'ع',
    langHref: '/',
  },
  category: { women: 'Women', men: 'Men', accessories: 'Accessories' },
  hero: {
    label: 'Film: the camera pulls back from the cloth of the Dahna coat to a woman standing on a dune at dawn.',
    collection: 'Collection 01',
    cloth: 'Double-faced wool, finished by hand',
    season: 'Autumn–Winter 2026',
    shop: 'Shop the collection',
    tagShop: 'Shop',
    hint: 'Scroll',
  },
  home: {
    edit: 'Collection 01',
    editLead: 'Eight pieces in wool, linen and leather, in sand, bone and night.',
    viewAll: 'View all',
    featureKicker: 'Dahna coat',
    featureTitle: 'The coat of the season',
    featureBody:
      'A long coat in double-faced wool, cut straight from a dropped shoulder. It is unlined, so it stays light through a Riyadh winter and warm on cold mornings.',
    featureCta: 'Shop the coat',
    shopBy: 'Shop by category',
    nightKicker: 'For the evening',
    nightTitle: 'The Layl abaya, and the Dahna coat in navy',
    nightBody: 'An abaya in matte black crepe, and the same coat in navy. Two pieces for evenings out and cool nights.',
    nightCta: 'Shop the Layl abaya',
    sunsetAhead: (time: string) => `Sunset in Riyadh today: ${time}`,
    sunsetPast: (time: string) => `The sun set in Riyadh today at ${time}`,
    storyKicker: 'Story',
    storyTitle: 'Clothes made for our climate',
    storyBody: 'Our winter is short, the mornings cold and the afternoons warm. So we choose cloth with weight, wide cuts, and colours taken from the sand.',
    storyCta: 'More about SARAB',
  },
  service: [
    { title: 'Delivery across Saudi Arabia', text: 'In 2 to 4 working days, free on orders over SAR 1,000.' },
    { title: 'Returns within 14 days', text: 'We collect from your door at no charge.' },
    { title: 'Gift wrapping', text: 'In a recycled paper box with a handwritten card.' },
  ],
  shop: {
    all: 'All pieces',
    items: (n: number) => `${n} ${n === 1 ? 'piece' : 'pieces'}`,
    colours: (n: number) => (n > 1 ? `${n} colours` : ''),
  },
  product: {
    colour: 'Colour',
    size: 'Size',
    sizeGuide: 'Size guide',
    selectSize: 'Select a size',
    add: 'Add to bag',
    added: 'Added to bag',
    details: 'Description',
    fit: 'Fit and size',
    fabric: 'Fabric and care',
    delivery: 'Delivery and returns',
    deliveryText:
      'Delivery across Saudi Arabia in 2 to 4 working days, free on orders over SAR 1,000. Return any piece within 14 days of delivery, in its original condition.',
    wearWith: 'Complete the look',
    home: 'Home',
    oneSize: 'One size',
    gallery: (name: string, n: number) => `${name}, image ${n}`,
    zoom: 'Zoom',
    prev: 'Previous',
    next: 'Next',
  },
  sizeGuide: {
    title: 'Size guide',
    note: 'Body measurements in centimetres, not garment measurements.',
    head: ['Size', 'Bust', 'Waist', 'Hip'],
  },
  bag: {
    title: 'Bag',
    empty: 'Your bag is empty.',
    emptyCta: 'Shop the collection',
    remove: 'Remove',
    qty: 'Quantity',
    subtotal: 'Subtotal',
    shippingNote: 'Delivery is calculated at the next step.',
    checkout: 'Checkout',
    size: 'Size',
    colour: 'Colour',
  },
  checkout: {
    title: 'Checkout',
    summary: 'Order summary',
    delivery: 'Delivery',
    free: 'Free',
    total: 'Total',
    empty: 'There is nothing in your bag.',
    demoKicker: 'Demo store',
    demoTitle: 'This is where your payment step goes.',
    demoBody:
      'SARAB is a demo store designed and built by SIMA Studio. The pieces, photographs and film were made for this demo, and no payment is taken here. On your store, this step connects to the payment provider you choose.',
    demoList: ['mada and Apple Pay through Moyasar', 'Instalments with Tabby and Tamara', 'Salla, Zid or Shopify', 'ZATCA-compliant invoices'],
    demoCta: 'Ask for a store like this',
    back: 'Back to the bag',
  },
  story: {
    kicker: 'Story',
    title: 'Clothes made for our climate.',
    paragraphs: [
      'SARAB began with a simple question: what does a coat look like if it is designed for Riyadh, not for a cold city far away? Winter here is short, the mornings are cold, the afternoons warm, and the wind is always there.',
      'So we choose cloth with weight, that falls in one line and settles after every gust. We cut from a dropped shoulder with wide sleeves, and we leave the coats unlined so they stay light.',
      'Our colours come from the same place: the sand of the Dahna, bone, and navy. Three colours that work together in any combination.',
    ],
    principles: [
      { title: 'Cloth with weight', text: 'Double-faced wool, matte crepe, washed linen and vegetable-tanned leather.' },
      { title: 'Wide cuts', text: 'Dropped shoulders, broad sleeves and full lengths that move with the body.' },
      { title: 'Small runs', text: 'Each piece is made in limited numbers, and remade only when it is asked for.' },
    ],
    care: {
      title: 'Care',
      text: 'Brush wool after each wear and let it rest on a wide hanger. Coats and abayas are dry clean only; wash linen by hand in cold water. Keep leather away from water and treat it with leather cream once a season.',
    },
    cta: 'Shop Collection 01',
  },
  footer: {
    help: 'Client services',
    helpLinks: ['Delivery', 'Returns', 'Size guide', 'Care'],
    house: 'SARAB',
    houseLinks: ['Story', 'Collection 01'],
    demo: 'A demo store designed and built by SIMA Studio. The pieces, photographs and film were made for this demo and are not for sale.',
    by: 'Design and build',
    rights: '© 2026 SARAB',
  },
  notFound: {
    kicker: 'Error 404',
    title: 'Page not found',
    body: 'The link may be wrong, or the page has moved.',
    cta: 'Back to the store',
    suggest: 'You may also like',
  },
};

export const COPY: Record<Locale, Copy> = { ar, en };
export type { Copy };

export const SIMA_URL = 'https://www.simastudio.it.com';
export const SITE_URL = 'https://sarab-theta.vercel.app';
