import type { Category } from './catalog';
import type { Locale } from './i18n';

const ar = {
  meta: {
    title: 'سراب — المجموعة الأولى',
    description: 'سراب: معاطف وعباءات وقطع من الصوف والكتان والجلد بألوان الرمل والليل. متجر تجريبي من تصميم سيما ستوديو.',
  },
  nav: {
    women: 'النساء',
    men: 'الرجال',
    accessories: 'الإكسسوارات',
    story: 'القصة',
    shopAll: 'تسوّق الكل',
    bag: 'الحقيبة',
    menu: 'القائمة',
    close: 'إغلاق',
    lang: 'English',
    langShort: 'EN',
    langHref: '/en',
  },
  category: {
    women: 'النساء',
    men: 'الرجال',
    accessories: 'الإكسسوارات',
  } satisfies Record<Category, string>,
  hero: {
    label: 'فيلم متحرك: الكاميرا تبتعد عن قماش معطف الدهناء حتى تظهر امرأة واقفة على كثيب وقت الفجر.',
    collection: 'المجموعة الأولى',
    cloth: 'صوف مزدوج الوجه، مشطّب يدويًا',
    season: 'خريف وشتاء 2026',
    shop: 'تسوّق المجموعة',
    tagShop: 'تسوّق',
    hint: 'مرّر',
  },
  home: {
    edit: 'المجموعة الأولى',
    editLead: 'ثماني قطع من الصوف والكتان والجلد، بألوان الرمل والعاج والليل.',
    viewAll: 'عرض الكل',
    featureKicker: 'معطف الدهناء',
    featureTitle: 'قماش يتحرك مع الريح',
    featureBody:
      'صوف مزدوج الوجه، بلا بطانة، بقصّة مستقيمة تبدأ من كتف منسدل. كل حافة مشطّبة يدويًا، فيبقى المعطف خفيفًا ويسقط بخط واحد.',
    featureCta: 'اكتشفي المعطف',
    shopBy: 'تسوّق حسب الفئة',
    nightKicker: 'بعد الغروب',
    nightTitle: 'عباءة ليل ومعطف الدهناء بلون الليل',
    nightBody: 'كريب حبري وصوف نيلي للأمسيات الباردة. القصّة نفسها، والوزن نفسه، بلون السماء بعد المغرب.',
    nightCta: 'تسوّقي عباءة ليل',
    sunsetAhead: (time: string) => `تغرب الشمس في الرياض اليوم الساعة ${time}.`,
    sunsetPast: (time: string) => `غربت الشمس في الرياض اليوم الساعة ${time}. هذه ساعة هذه القطع.`,
    storyKicker: 'القصة',
    storyTitle: 'ملابس مفصّلة للصحراء',
    storyBody: 'نبدأ كل قطعة من الريح والضوء المنخفض. قماش له وزن، قصّات واسعة، وألوان من الرمل.',
    storyCta: 'اقرأ القصة',
  },
  service: [
    { title: 'توصيل داخل المملكة', text: 'خلال 2 إلى 4 أيام عمل، ومجاني للطلبات فوق 1,000 ر.س.' },
    { title: 'إرجاع خلال 14 يومًا', text: 'نستلم القطعة من بابك دون رسوم.' },
    { title: 'تغليف للهدايا', text: 'في علبة من الورق المعاد تدويره مع بطاقة مكتوبة بخط اليد.' },
  ],
  shop: {
    all: 'كل القطع',
    items: (n: number) => (n === 1 ? 'قطعة واحدة' : n === 2 ? 'قطعتان' : n <= 10 ? `${n} قطع` : `${n} قطعة`),
    colours: (n: number) => (n > 1 ? `${n} ألوان` : ''),
  },
  product: {
    colour: 'اللون',
    size: 'المقاس',
    sizeGuide: 'دليل المقاسات',
    selectSize: 'اختر المقاس',
    add: 'أضف إلى الحقيبة',
    added: 'أُضيفت إلى الحقيبة',
    details: 'الوصف',
    fit: 'القصّة والمقاس',
    fabric: 'الخامة والعناية',
    delivery: 'التوصيل والإرجاع',
    deliveryText:
      'توصيل داخل المملكة خلال 2 إلى 4 أيام عمل، ومجاني للطلبات فوق 1,000 ر.س. يمكنك إرجاع القطعة خلال 14 يومًا من استلامها بحالتها الأصلية.',
    wearWith: 'تُلبس مع',
    home: 'الرئيسية',
    oneSize: 'مقاس واحد',
    gallery: (name: string, n: number) => `${name}، صورة ${n}`,
    zoom: 'تكبير',
    prev: 'السابقة',
    next: 'التالية',
  },
  sizeGuide: {
    title: 'دليل المقاسات',
    note: 'المقاسات بالسنتيمتر وتقيس الجسم، لا القطعة.',
    head: ['المقاس', 'الصدر', 'الخصر', 'الورك'],
  },
  bag: {
    title: 'الحقيبة',
    empty: 'حقيبتك فارغة.',
    emptyCta: 'تسوّق المجموعة',
    remove: 'إزالة',
    qty: 'الكمية',
    subtotal: 'المجموع الفرعي',
    shippingNote: 'تُحسب رسوم التوصيل في الخطوة التالية.',
    checkout: 'إتمام الطلب',
    size: 'المقاس',
    colour: 'اللون',
  },
  checkout: {
    title: 'إتمام الطلب',
    summary: 'ملخص الطلب',
    delivery: 'التوصيل',
    free: 'مجاني',
    total: 'الإجمالي',
    empty: 'لا توجد قطع في حقيبتك.',
    demoKicker: 'متجر تجريبي',
    demoTitle: 'هنا يبدأ الدفع في متجرك.',
    demoBody:
      'سراب متجر تجريبي صمّمته ونفّذته سيما ستوديو. القطع والصور والفيلم مصنوعة لهذا العرض، ولا يوجد دفع حقيقي هنا. في متجرك، تتصل هذه الخطوة ببوابة الدفع التي تختارها.',
    demoList: ['مدى وApple Pay عبر ميسّر', 'التقسيط مع تابي وتمارا', 'سلة أو زد أو Shopify', 'فواتير متوافقة مع هيئة الزكاة'],
    demoCta: 'اطلب متجرًا مثل هذا',
    back: 'العودة إلى الحقيبة',
  },
  story: {
    kicker: 'القصة',
    title: 'نصمّم للريح.',
    paragraphs: [
      'بدأت سراب من سؤال بسيط: كيف يبدو معطف صُمّم للرياض، لا لمدينة باردة بعيدة؟ الشتاء هنا قصير، والصباح بارد، والظهيرة دافئة، والريح حاضرة دائمًا.',
      'لذلك نختار أقمشة لها وزن، تسقط بخط واحد وتعود إلى مكانها بعد كل هبّة. نقصّ بكتف منسدل وأكمام واسعة، ونترك المعاطف بلا بطانة حتى تبقى خفيفة.',
      'ألواننا من المكان نفسه: رمل الدهناء عند الفجر، عاج الضوء الأول، ونيلي السماء بعد المغرب. ثلاثة ألوان تُلبس معًا في كل تركيبة.',
    ],
    principles: [
      { title: 'قماش له وزن', text: 'صوف مزدوج الوجه، كريب مطفي، كتان مغسول، وجلد مدبوغ نباتيًا.' },
      { title: 'قصّات واسعة', text: 'كتف منسدل وأكمام عريضة وأطوال كاملة تتحرك مع الجسم.' },
      { title: 'كميات قليلة', text: 'نصنع كل قطعة بعدد محدود، ونعيد إنتاج ما يُطلب فقط.' },
    ],
    care: {
      title: 'العناية بالقطع',
      text: 'يُنظَّف الصوف بالفرشاة بعد كل لبسة، ويُعلَّق على علاقة عريضة ليرتاح. المعاطف والعباءات للتنظيف الجاف فقط، والكتان يُغسل باليد بماء بارد. يُبعَد الجلد عن الماء، ويُغذّى مرة كل موسم.',
    },
    cta: 'تسوّق المجموعة الأولى',
  },
  footer: {
    help: 'خدمة العملاء',
    helpLinks: ['التوصيل', 'الإرجاع', 'دليل المقاسات', 'العناية بالقطع'],
    house: 'سراب',
    houseLinks: ['القصة', 'المجموعة الأولى'],
    demo: 'متجر تجريبي من تصميم وتنفيذ سيما ستوديو. القطع والصور والفيلم مصنوعة لهذا العرض، ولا تُباع.',
    by: 'تصميم وتنفيذ',
    rights: '© 2026 سراب',
  },
  notFound: {
    kicker: 'خطأ 404',
    title: 'سراب.',
    body: 'ما رأيته من بعيد لم يكن هنا. الصفحة التي تبحث عنها غير موجودة، أو انتقلت.',
    cta: 'العودة إلى المتجر',
    suggest: 'قطع قد تبحث عنها',
  },
};

type Copy = typeof ar;

const en: Copy = {
  meta: {
    title: 'SARAB — Collection 01',
    description: 'SARAB: coats, abayas and pieces in wool, linen and leather, in the colours of sand and night. A demo store designed by SIMA Studio.',
  },
  nav: {
    women: 'Women',
    men: 'Men',
    accessories: 'Accessories',
    story: 'Story',
    shopAll: 'Shop all',
    bag: 'Bag',
    menu: 'Menu',
    close: 'Close',
    lang: 'العربية',
    langShort: 'ع',
    langHref: '/',
  },
  category: { women: 'Women', men: 'Men', accessories: 'Accessories' },
  hero: {
    label: 'Film: the camera pulls back from the cloth of the Dahna coat to a woman standing on a dune at dawn.',
    collection: 'Collection 01',
    cloth: 'Double-faced wool, finished by hand',
    season: 'Autumn–Winter 2026',
    shop: 'Shop the collection',
    tagShop: 'Shop',
    hint: 'Scroll',
  },
  home: {
    edit: 'Collection 01',
    editLead: 'Eight pieces in wool, linen and leather, in sand, bone and night.',
    viewAll: 'View all',
    featureKicker: 'Dahna coat',
    featureTitle: 'Cloth that moves with the wind',
    featureBody:
      'Double-faced wool, unlined, cut straight from a dropped shoulder. Every edge is finished by hand, so the coat stays light and falls in one line.',
    featureCta: 'Discover the coat',
    shopBy: 'Shop by category',
    nightKicker: 'After sunset',
    nightTitle: 'The Layl abaya and the Dahna coat in Night',
    nightBody: 'Ink crepe and indigo wool for cool evenings. The same cut and weight, in the colour of the sky after sunset.',
    nightCta: 'Shop the Layl abaya',
    sunsetAhead: (time: string) => `The sun sets over Riyadh today at ${time}.`,
    sunsetPast: (time: string) => `The sun set over Riyadh today at ${time}. This is the hour these pieces are for.`,
    storyKicker: 'Story',
    storyTitle: 'Clothes cut for the desert',
    storyBody: 'Every piece starts with the wind and low light. Cloth with weight, wide cuts, and colours taken from the sand.',
    storyCta: 'Read the story',
  },
  service: [
    { title: 'Delivery across Saudi Arabia', text: 'In 2 to 4 working days, free on orders over SAR 1,000.' },
    { title: 'Returns within 14 days', text: 'We collect from your door at no charge.' },
    { title: 'Gift wrapping', text: 'In a recycled paper box with a handwritten card.' },
  ],
  shop: {
    all: 'All pieces',
    items: (n: number) => `${n} ${n === 1 ? 'piece' : 'pieces'}`,
    colours: (n: number) => (n > 1 ? `${n} colours` : ''),
  },
  product: {
    colour: 'Colour',
    size: 'Size',
    sizeGuide: 'Size guide',
    selectSize: 'Select a size',
    add: 'Add to bag',
    added: 'Added to bag',
    details: 'Description',
    fit: 'Fit and size',
    fabric: 'Fabric and care',
    delivery: 'Delivery and returns',
    deliveryText:
      'Delivery across Saudi Arabia in 2 to 4 working days, free on orders over SAR 1,000. Return any piece within 14 days of delivery, in its original condition.',
    wearWith: 'Wear it with',
    home: 'Home',
    oneSize: 'One size',
    gallery: (name: string, n: number) => `${name}, image ${n}`,
    zoom: 'Zoom',
    prev: 'Previous',
    next: 'Next',
  },
  sizeGuide: {
    title: 'Size guide',
    note: 'Body measurements in centimetres, not garment measurements.',
    head: ['Size', 'Bust', 'Waist', 'Hip'],
  },
  bag: {
    title: 'Bag',
    empty: 'Your bag is empty.',
    emptyCta: 'Shop the collection',
    remove: 'Remove',
    qty: 'Quantity',
    subtotal: 'Subtotal',
    shippingNote: 'Delivery is calculated at the next step.',
    checkout: 'Checkout',
    size: 'Size',
    colour: 'Colour',
  },
  checkout: {
    title: 'Checkout',
    summary: 'Order summary',
    delivery: 'Delivery',
    free: 'Free',
    total: 'Total',
    empty: 'There is nothing in your bag.',
    demoKicker: 'Demo store',
    demoTitle: 'This is where your payment step goes.',
    demoBody:
      'SARAB is a demo store designed and built by SIMA Studio. The pieces, photographs and film were made for this demo, and no payment is taken here. On your store, this step connects to the payment provider you choose.',
    demoList: ['mada and Apple Pay through Moyasar', 'Instalments with Tabby and Tamara', 'Salla, Zid or Shopify', 'ZATCA-compliant invoices'],
    demoCta: 'Ask for a store like this',
    back: 'Back to the bag',
  },
  story: {
    kicker: 'Story',
    title: 'We design for the wind.',
    paragraphs: [
      'SARAB began with a simple question: what does a coat look like if it is designed for Riyadh, not for a cold city far away? Winter here is short, the mornings are cold, the afternoons warm, and the wind is always there.',
      'So we choose cloth with weight, that falls in one line and settles after every gust. We cut from a dropped shoulder with wide sleeves, and we leave the coats unlined so they stay light.',
      'Our colours come from the same place: the sand of the Dahna at dawn, the bone of first light, and the indigo of the sky after sunset. Three colours that wear together in every combination.',
    ],
    principles: [
      { title: 'Cloth with weight', text: 'Double-faced wool, matte crepe, washed linen and vegetable-tanned leather.' },
      { title: 'Wide cuts', text: 'Dropped shoulders, broad sleeves and full lengths that move with the body.' },
      { title: 'Small runs', text: 'Each piece is made in limited numbers, and remade only when it is asked for.' },
    ],
    care: {
      title: 'Care',
      text: 'Brush wool after each wear and let it rest on a wide hanger. Coats and abayas are dry clean only; wash linen by hand in cold water. Keep leather away from water and feed it once a season.',
    },
    cta: 'Shop Collection 01',
  },
  footer: {
    help: 'Client services',
    helpLinks: ['Delivery', 'Returns', 'Size guide', 'Care'],
    house: 'SARAB',
    houseLinks: ['Story', 'Collection 01'],
    demo: 'A demo store designed and built by SIMA Studio. The pieces, photographs and film were made for this demo and are not for sale.',
    by: 'Design and build',
    rights: '© 2026 SARAB',
  },
  notFound: {
    kicker: 'Error 404',
    title: 'A mirage.',
    body: 'What you saw from afar was never here. The page you are looking for does not exist, or it has moved.',
    cta: 'Back to the store',
    suggest: 'Pieces you may be looking for',
  },
};

export const COPY: Record<Locale, Copy> = { ar, en };
export type { Copy };

export const SIMA_URL = 'https://www.simastudio.it.com';
export const SITE_URL = 'https://sarab-theta.vercel.app';
